### ISSUE TITLE
:white_check_mark: svg 파일 업로드 및 폴더 구조 예시 

### ISSUE THREAD

**Issue by wooleejaan** [codeit-bootcamp-frontend/0-the-julge-young-developers#3]
### Description

프로젝트에 필요한 이미지 리소스(.svg) 업로드 (where: public/images/)

### To-do

- [ ] 이미지 리소스 업로드 
- [ ] 폴더 구조 예시 디렉토리 생성

**Comment by shyjnnn** [comment]
리소스가 다 있는건가요?
